//! Offline end-to-end tests: a fake yt-dlp serves generated media, ffmpeg runs for real
//! (through a wrapper that counts encodes) and the charts are generated by the real
//! itg-charter library (without Demucs). Skipped when ffmpeg/ffprobe are missing.

use std::path::{Path, PathBuf};
use std::process::{Command, Output};

fn has(tool: &str) -> bool {
    Command::new(tool)
        .arg("-version")
        .output()
        .is_ok_and(|o| o.status.success())
}

fn ffmpeg(args: &[&str]) {
    let st = Command::new("ffmpeg")
        .args(["-y", "-nostdin", "-loglevel", "error"])
        .args(args)
        .status()
        .unwrap();
    assert!(st.success(), "ffmpeg {args:?}");
}

fn probe(file: &Path, entries: &str) -> String {
    let out = Command::new("ffprobe")
        .args([
            "-v",
            "error",
            "-show_entries",
            entries,
            "-of",
            "default=nw=1",
        ])
        .arg(file)
        .output()
        .unwrap();
    String::from_utf8(out.stdout).unwrap()
}

fn write_script(path: &Path, body: &str) {
    std::fs::write(path, body).unwrap();
    let mut perm = std::fs::metadata(path).unwrap().permissions();
    std::os::unix::fs::PermissionsExt::set_mode(&mut perm, 0o755);
    std::fs::set_permissions(path, perm).unwrap();
}

/// Value of a `#KEY:...;` tag.
fn tag<'a>(sm: &'a str, key: &str) -> Option<&'a str> {
    let marker = format!("#{key}:");
    let start = sm.find(&marker)? + marker.len();
    Some(&sm[start..start + sm[start..].find(';')?])
}

/// (difficulty, meter) of every chart of a `.sm`.
fn charts(sm: &str) -> Vec<(String, u32)> {
    sm.split("#NOTES:")
        .skip(1)
        .map(|c| {
            let f: Vec<&str> = c.split(':').map(str::trim).collect();
            (f[2].to_string(), f[3].parse().unwrap())
        })
        .collect()
}

struct Env {
    root: PathBuf,
}

impl Env {
    /// Source media, a fake yt-dlp serving them and a logging ffmpeg wrapper.
    fn new(name: &str) -> Env {
        let root = std::env::temp_dir().join(format!("itg-yt-test-{}-{name}", std::process::id()));
        let _ = std::fs::remove_dir_all(&root);
        let src = root.join("src");
        std::fs::create_dir_all(&src).unwrap();
        let s = |f: &str| src.join(f).to_string_lossy().into_owned();
        // 12 s of kick-like pulses at 120 BPM, so that itg-charter finds a beat.
        ffmpeg(&[
            "-f",
            "lavfi",
            "-i",
            "aevalsrc=sin(2*PI*60*t)*exp(-30*mod(t\\,0.5)):s=44100:d=12",
            "-ac",
            "2",
            &s("audio.mp3"),
        ]);
        ffmpeg(&[
            "-f",
            "lavfi",
            "-i",
            "testsrc2=size=320x180:rate=25:duration=2",
            "-pix_fmt",
            "yuv420p",
            &s("video.mp4"),
        ]);
        ffmpeg(&[
            "-f",
            "lavfi",
            "-i",
            "testsrc=size=1280x720",
            "-frames:v",
            "1",
            &s("thumb.jpg"),
        ]);
        // Metadata served by the fake yt-dlp, per video id ("broken" has none).
        std::fs::write(
            src.join("info-abc123.json"),
            r#"{"id":"abc123","title":"Some Artist - Great Song (Official Video) [4K]","uploader":"SomeArtistVEVO","webpage_url":"https://www.youtube.com/watch?v=abc123"}"#,
        )
        .unwrap();
        std::fs::write(
            src.join("info-def456.json"),
            r#"{"id":"def456","title":"Whatever (Official Audio)","track":"Second Song","artists":["Band A","Band B"],"uploader":"Label","webpage_url":"https://www.youtube.com/watch?v=def456"}"#,
        )
        .unwrap();
        // Fake yt-dlp: -j prints one JSON line per URL; otherwise copies the requested
        // media to the -o template (with %(ext)s replaced). Downloads are logged, and can
        // be made to fail: flaky-meta (one id), crash-* token files (one crash per token;
        // `rm` is atomic, so parallel downloads never consume the same token).
        write_script(
            &root.join("yt-dlp"),
            &format!(
                r#"#!/bin/sh
SRC='{src}'
case " $* " in *" -j "*)
  for a in "$@"; do
    case "$a" in http*)
      id=$(echo "$a" | sed -n 's/.*v=\([^&]*\).*/\1/p')
      if [ "$(cat "$SRC/flaky-meta" 2>/dev/null)" = "$id" ]; then
        rm "$SRC/flaky-meta"; echo "ERROR: [youtube] $id: temporary failure" >&2
      elif [ -f "$SRC/info-$id.json" ]; then cat "$SRC/info-$id.json"; echo
      else echo "ERROR: [youtube] $id: Video unavailable" >&2; fi;;
    esac
  done
  exit 0;;
esac
for t in "$SRC"/crash-*; do
  if rm "$t" 2>/dev/null; then echo "ERROR: simulated crash" >&2; exit 1; fi
done
out=""; fmt=""; thumb=0; prev=""
for a in "$@"; do
  case "$a" in --write-thumbnail) thumb=1;; esac
  [ "$prev" = "-o" ] && out="$a"
  [ "$prev" = "-f" ] && fmt="$a"
  prev="$a"
done
if [ $thumb = 1 ]; then f=thumb.jpg; ext=jpg
elif echo "$fmt" | grep -q '^bestaudio'; then f=audio.mp3; ext=mp3
else f=video.mp4; ext=mp4; fi
echo "$f" >> "$SRC/downloads.log"
cp "$SRC/$f" "$(echo "$out" | sed "s/%(ext)s/$ext/")"
"#,
                src = src.display()
            ),
        );
        write_script(
            &root.join("ffmpeg"),
            &format!(
                "#!/bin/sh\necho x >> '{src}/encodes.log'\nexec ffmpeg \"$@\"\n",
                src = src.display()
            ),
        );
        Env { root }
    }

    /// Runs itg-yt on `urls` without Demucs (no check of the exit status).
    fn run_urls(&self, urls: &[&str], out: &str, extra: &[&str]) -> Output {
        Command::new(env!("CARGO_BIN_EXE_itg-yt"))
            .args(urls)
            .arg("-o")
            .arg(self.root.join(out))
            .arg("--cache")
            .arg(self.root.join("cache"))
            .arg("--no-stems")
            .args(extra)
            .env("ITG_YT_DLP", self.root.join("yt-dlp"))
            .env("ITG_FFMPEG", self.root.join("ffmpeg"))
            .env("ITG_YT_RETRY_PAUSE_MS", "10")
            .output()
            .unwrap()
    }

    /// Runs itg-yt on the "Great Song" video and returns its `.sm`.
    fn run(&self, out: &str, extra: &[&str]) -> PathBuf {
        let o = self.run_urls(
            &["https://www.youtube.com/watch?v=abc123&list=RDxyz&index=3"],
            out,
            extra,
        );
        assert!(o.status.success(), "{}", String::from_utf8_lossy(&o.stderr));
        PathBuf::from(String::from_utf8(o.stdout).unwrap().trim())
    }

    fn file(&self, f: &str) -> String {
        std::fs::read_to_string(self.root.join("src").join(f)).unwrap_or_default()
    }
}

impl Drop for Env {
    fn drop(&mut self) {
        let _ = std::fs::remove_dir_all(&self.root);
    }
}

/// Small, fast video settings for the tests (the defaults are 1080p / medium).
const FAST: [&str; 4] = ["--video-height", "144", "--video-preset", "ultrafast"];

fn ffmpeg_ok() -> bool {
    let ok = has("ffmpeg") && has("ffprobe");
    if !ok {
        eprintln!("ffmpeg not installed, skipping");
    }
    ok
}

#[test]
fn builds_a_complete_song_folder() {
    if !ffmpeg_ok() {
        return;
    }
    let env = Env::new("full");
    let sm = env.run("songs", &FAST);
    let dir = env.root.join("songs/Great Song");
    assert_eq!(sm, dir.join("Great Song.sm"));

    let ogg = probe(
        &dir.join("Great Song.ogg"),
        "stream=codec_name,sample_rate,channels",
    );
    assert!(
        ogg.contains("codec_name=vorbis")
            && ogg.contains("sample_rate=44100")
            && ogg.contains("channels=2"),
        "{ogg}"
    );
    let video = probe(
        &dir.join("Great Song-bg.mp4"),
        "stream=codec_type,codec_name,height",
    );
    assert!(
        video.contains("codec_name=h264") && video.contains("height=144"),
        "{video}"
    );
    assert!(
        !video.contains("codec_type=audio"),
        "background video must be silent"
    );
    for (png, w, h) in [
        ("bn.png", 418, 164),
        ("bg.png", 1920, 1080),
        ("jacket.png", 512, 512),
    ] {
        let p = probe(&dir.join(png), "stream=width,height");
        assert!(
            p.contains(&format!("width={w}")) && p.contains(&format!("height={h}")),
            "{png}: {p}"
        );
    }

    // The simfile, written by itg-charter: names cleaned from the YouTube title, the
    // visuals and the movie declared, the charts of the default profile.
    let text = std::fs::read_to_string(&sm).unwrap();
    assert_eq!(tag(&text, "TITLE"), Some("Great Song"));
    assert_eq!(tag(&text, "ARTIST"), Some("Some Artist"));
    assert_eq!(tag(&text, "MUSIC"), Some("Great Song.ogg"));
    assert_eq!(tag(&text, "BANNER"), Some("bn.png"));
    assert_eq!(tag(&text, "BACKGROUND"), Some("bg.png"));
    assert_eq!(tag(&text, "JACKET"), Some("jacket.png"));
    // Marked as generated, so that itg-charter never trains or evaluates on it if the
    // output folder is linked into the game's Songs (Simfile::is_generated).
    assert!(tag(&text, "CREDIT").unwrap().contains("itg-charter"));
    let bg = tag(&text, "BGCHANGES").unwrap();
    assert!(
        bg.ends_with("=Great Song-bg.mp4=1.000=0=0=0=StretchNoLoop===="),
        "{bg}"
    );
    let default_meters = itg_charter::song::Profile::default().meters();
    assert_eq!(charts(&text).len(), default_meters.len());

    // A second run downloads and encodes nothing, and gives the same simfile.
    assert_eq!(
        env.file("downloads.log").lines().count(),
        3,
        "audio, video, thumbnail"
    );
    assert_eq!(
        env.file("encodes.log").lines().count(),
        5,
        "audio, 3 images, video"
    );
    let again = env.run("songs2", &FAST);
    assert_eq!(
        env.file("downloads.log").lines().count(),
        3,
        "nothing downloaded twice"
    );
    assert_eq!(
        env.file("encodes.log").lines().count(),
        5,
        "nothing encoded twice"
    );
    assert_eq!(std::fs::read(&sm).unwrap(), std::fs::read(&again).unwrap());

    // Another video quality is a new encode, the rest comes from the cache.
    env.run(
        "songs3",
        &["--video-height", "100", "--video-preset", "ultrafast"],
    );
    assert_eq!(
        env.file("encodes.log").lines().count(),
        6,
        "only the video is re-encoded"
    );
}

#[test]
fn meters_profiles_and_difficulties() {
    if !ffmpeg_ok() {
        return;
    }
    let env = Env::new("meters");
    let text = |sm: PathBuf| std::fs::read_to_string(sm).unwrap();

    let got = charts(&text(env.run("a", &["--no-video", "-m", "2-3"])));
    assert_eq!(got.iter().map(|c| c.1).collect::<Vec<_>>(), [2, 3]);

    let got = charts(&text(env.run("b", &["--no-video", "-p", "beginner"])));
    assert_eq!(got.len(), 4, "{got:?}");

    let got = charts(&text(env.run("c", &["--no-video", "-d", "easy,hard"])));
    let names: Vec<&str> = got.iter().map(|c| c.0.as_str()).collect();
    assert_eq!(names, ["Easy", "Hard"]);

    // An invalid meter is refused before anything is downloaded.
    let fresh = Env::new("meters-bad");
    let o = fresh.run_urls(
        &["https://www.youtube.com/watch?v=abc123"],
        "d",
        &["-m", "0-4"],
    );
    assert!(!o.status.success());
    assert!(String::from_utf8_lossy(&o.stderr).contains("out of range"));
    assert!(fresh.file("downloads.log").is_empty());
}

#[test]
fn video_is_never_upscaled() {
    if !ffmpeg_ok() {
        return;
    }
    let env = Env::new("noupscale");
    // Default height is 1080 but the source is 180 pixels high.
    let sm = env.run("songs", &["--video-preset", "ultrafast", "-m", "3"]);
    let video = probe(
        &sm.parent().unwrap().join("Great Song-bg.mp4"),
        "stream=height",
    );
    assert!(video.contains("height=180"), "{video}");
}

#[test]
fn no_video_option() {
    if !ffmpeg_ok() {
        return;
    }
    let env = Env::new("novideo");
    let sm = env.run(
        "songs",
        &["--no-video", "--title", "X", "--artist", "Y", "-m", "3"],
    );
    let dir = sm.parent().unwrap();
    assert!(!dir.join("X-bg.mp4").exists());
    assert!(!env.file("downloads.log").contains("video.mp4"));
    let text = std::fs::read_to_string(&sm).unwrap();
    assert_eq!(tag(&text, "BGCHANGES"), Some(""));
    assert_eq!(
        (tag(&text, "TITLE"), tag(&text, "ARTIST")),
        (Some("X"), Some("Y"))
    );
}

#[test]
fn several_urls_are_processed_and_failures_reported() {
    if !ffmpeg_ok() {
        return;
    }
    let env = Env::new("multi");
    let urls = [
        "https://www.youtube.com/watch?v=abc123",
        "https://www.youtube.com/watch?v=def456",
        "https://www.youtube.com/watch?v=broken",
        // duplicate of the first one: processed once
        "https://www.youtube.com/watch?v=abc123&list=RDxyz",
    ];
    let mut extra = FAST.to_vec();
    extra.extend(["--jobs", "3", "-m", "2,4"]);
    let o = env.run_urls(&urls, "songs", &extra);
    let stderr = String::from_utf8_lossy(&o.stderr);
    assert!(!o.status.success(), "a missing video makes the run fail");
    assert!(stderr.contains("broken: Video unavailable"), "{stderr}");
    assert!(stderr.contains("2 song(s) ready, 1 failed"), "{stderr}");

    // Both songs are complete; stdout lists their simfiles in URL order.
    let sms: Vec<String> = String::from_utf8(o.stdout)
        .unwrap()
        .lines()
        .map(String::from)
        .collect();
    let songs = env.root.join("songs");
    assert_eq!(
        sms,
        [
            songs
                .join("Great Song/Great Song.sm")
                .to_string_lossy()
                .into_owned(),
            songs
                .join("Second Song/Second Song.sm")
                .to_string_lossy()
                .into_owned(),
        ]
    );
    let second = std::fs::read_to_string(&sms[1]).unwrap();
    // yt-dlp music metadata: track + list of artists.
    assert_eq!(tag(&second, "ARTIST"), Some("Band A, Band B"));
    assert!(
        tag(&second, "BGCHANGES")
            .unwrap()
            .contains("=Second Song-bg.mp4=")
    );
    assert_eq!(
        env.file("downloads.log").lines().count(),
        6,
        "3 files per song, once"
    );
}

#[test]
fn urls_from_a_batch_file() {
    if !ffmpeg_ok() {
        return;
    }
    let env = Env::new("batch");
    let list = env.root.join("urls.txt");
    std::fs::write(
        &list,
        "# my songs\nhttps://www.youtube.com/watch?v=def456\n\n  https://www.youtube.com/watch?v=abc123  \n",
    )
    .unwrap();
    let o = env.run_urls(
        &[],
        "songs",
        &["--no-video", "-m", "3", "-a", list.to_str().unwrap()],
    );
    assert!(o.status.success(), "{}", String::from_utf8_lossy(&o.stderr));
    let out = String::from_utf8(o.stdout).unwrap();
    assert_eq!(out.lines().count(), 2, "{out}");
    assert!(
        out.lines().next().unwrap().ends_with("Second Song.sm"),
        "file order is kept"
    );
}

#[test]
fn title_override_needs_a_single_video() {
    if !ffmpeg_ok() {
        return;
    }
    let env = Env::new("override");
    let urls = [
        "https://www.youtube.com/watch?v=abc123",
        "https://www.youtube.com/watch?v=def456",
    ];
    let o = env.run_urls(&urls, "songs", &["--title", "X"]);
    assert!(!o.status.success());
    assert!(String::from_utf8_lossy(&o.stderr).contains("only make sense with a single video"));
}

/// The next `n` downloads of the fake yt-dlp crash.
fn crash_tokens(src: &Path, n: usize) {
    for i in 0..n {
        std::fs::write(src.join(format!("crash-{i}")), "").unwrap();
    }
}

#[test]
fn yt_dlp_failures_are_retried() {
    if !ffmpeg_ok() {
        return;
    }
    let env = Env::new("retry");
    let src = env.root.join("src");
    // def456's metadata fails once, and the first two downloads crash.
    std::fs::write(src.join("flaky-meta"), "def456").unwrap();
    crash_tokens(&src, 2);
    let urls = [
        "https://www.youtube.com/watch?v=abc123",
        "https://www.youtube.com/watch?v=def456",
    ];
    let o = env.run_urls(&urls, "songs", &["--no-video", "--jobs", "1", "-m", "3"]);
    let stderr = String::from_utf8_lossy(&o.stderr);
    assert!(o.status.success(), "{stderr}");
    assert!(stderr.contains("1 URL(s) failed, retry 1/3"), "{stderr}");
    // Two crashes, retried (on the same download or on two parallel ones).
    assert_eq!(
        stderr.matches("download failed, retry").count(),
        2,
        "{stderr}"
    );
    assert_eq!(String::from_utf8(o.stdout).unwrap().lines().count(), 2);
}

#[test]
fn retries_are_bounded() {
    if !ffmpeg_ok() {
        return;
    }
    let env = Env::new("retry-bounded");
    crash_tokens(&env.root.join("src"), 100);
    let o = env.run_urls(
        &["https://www.youtube.com/watch?v=abc123"],
        "songs",
        &["--no-video", "--yt-retries", "2", "-m", "3"],
    );
    let stderr = String::from_utf8_lossy(&o.stderr);
    assert!(!o.status.success());
    assert!(
        stderr.contains("retry 2/2") && !stderr.contains("retry 3/"),
        "{stderr}"
    );
    assert!(stderr.contains("0 song(s) ready, 1 failed"), "{stderr}");
}
